### ISSUE TITLE
Ship stuff

### ISSUE THREAD

**Issue by Axipeiki** [Conquest-Reforged/Indev#296] opened 2021-03-05 12:26 UTC
Could we possibly get a cannon block along with smaller wheels or something like that? I know about the artillery block but its not centered and it looks weird. Also new ropes would be nice to have and one last thing, rusted copper maybe?

**Comment by CreativeRealms** [comment] 2021-03-05 16:03
Duplicate of #294

**Closed by CreativeRealms** 2021-03-05 16:03 UTC
Labels: Conquest Reforged, Texture/Asset
