### ISSUE TITLE
Horizontal beam block texture glitch.

### ISSUE THREAD

**Issue by Mokumer** [Conquest-Reforged/Indev#125] opened 2020-05-26 20:06 UTC
**Mod Version & Build Number**    
ConquestReforged-mc1.15.2-4.0.0-v0.41.jar

**Forge Version**    
1.15.2-forge-31.1.0

**Describe the bug**    
When placing a horitzontal beam under any block, the bottom texture of that block becomes invisible, this happens to full block as well as stairs, slabs, walls etc. 

**Screenshots/Video**    
![image](https://user-images.githubusercontent.com/58232628/82945069-99118c00-9f9c-11ea-968d-bd83f2864ff5.png)

**System Information (optional)**    
Total RAM:    16 GB
Allocated RAM:    6 GB
CPU:    Intel Core i7-9750H
GPU:    NVIDIA GeForce GTX 1160 Ti

**Additional context**    
When starting the game, the mod says that I am missing optifine as a dependency, I do however have optifine installed and the optifine related textures work fine for me.

**Comment by HIPPOKLEIDES** [comment] 2020-05-26 20:22
duplicate of #120 
has been fixed

**Closed by HIPPOKLEIDES** 2020-05-26 20:22 UTC
Labels: Bug, Conquest Reforged
