### ISSUE TITLE
Rack of pistols weird pixel in hand model

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#37] opened 2020-02-04 13:47 UTC
![2020-02-04_15 40 47](https://user-images.githubusercontent.com/33978024/73750334-a7296b80-4765-11ea-8f09-0c77e9344ec4.png)

**Comment by HIPPOKLEIDES** [comment] 2020-02-04 20:21
Fixed in build 61+
For future reference, this is caused by random semi-transparent pixels in a texture.

**Closed by HIPPOKLEIDES** 2020-02-04 20:21 UTC
Labels: Bug, Conquest Reforged, Texture/Asset
