### ISSUE TITLE
Round wooden stool hand model

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/Indev#34] opened 2020-02-04 13:34 UTC
![2020-02-04_07 08 54](https://user-images.githubusercontent.com/33978024/73749282-b8717880-4763-11ea-8bda-589d591c739f.png)

**Comment by HIPPOKLEIDES** [comment] 2020-02-04 20:21
Fixed in build 61+
For future reference, this is caused by random semi-transparent pixels in a texture.

**Closed by HIPPOKLEIDES** 2020-02-04 20:21 UTC
Labels: Bug, Conquest Reforged
